class Hero:
	hero_name = {
		"树精卫士": "Treant Protector",
		"死亡先知": "Death Prophet",
		"干扰者": "Disruptor",
		"小小": "Tiny",
		"水晶室女": "Crystal Maiden",
		"沙王": "Sand King",
		"神谕者": "Oracle",
		"狼人": "Lycan",
		"幻影刺客": "Phantom Assasin",
		"亚巴顿": "Abaddon",
		"祈求者": "Invoker",
		"昆卡": "Kunkka",
		"米波": "Meepo",
		"艾欧": "Io",
		"莉娜": "Lina",
		"不朽尸王": "Undying",
		"熊战士": "Ursa",
		"蝙蝠骑士": "Batrider",
		"马格纳斯": "Magnus",
		"末日使者": "Doom Bringer",
		"龙骑士": "Dragon Knight",
		"哈斯卡": "Huskar",
		"司夜刺客": "Nyx Assasin",
		"娜迦海妖": "Naga Siren",
		"术士": "Warlock",
		"冥界亚龙": "Viper",
		"拉比克": "Rubick",
		"敌法师": "Anti Mage",
		"斯温": "Sven",
		"食人魔魔法师": "Ogre Magi",
		"米拉娜": "Mirana",
		"陈": "Chen",
		"巨牙海民": "Tusk",
		"痛苦女王": "Queen of Pain",
		"伐木机": "Timbersaw",
		"沉默术士": "Silencer",
		"噬魂鬼": "Lifestealer",
		"修补匠": "Tinker",
		"帕格纳": "Pugna",
		"黑暗贤者": "Dark Seer",
		"殁境神蚀者": "Obsidian Destroyer",
		"戴泽": "Dazzle",
		"祸乱之源": "Bane",
		"杰奇洛": "Jakiro",
		"矮人直升机": "Gyrocopter",
		"影魔": "Shadow Fiend",
		"德鲁伊": "Lone Druid",
		"军团指挥官": "Legion Commander",
		"赏金猎人": "Bounty Hunter",
		"远古冰魄": "Ancient Apparition",
		"力丸": "Riki",
		"暗影萨满": "Shadow Shaman",
		"光之守卫": "Keeper of the Light",
		"嗜血狂魔": "Bloodseeker",
		"魅惑魔女": "Enchantress",
		"风行者": "Wind Ranger",
		"宙斯": "Zeus",
		"斯拉克": "Slark",
		"钢背兽": "Bristleback",
		"变体精灵": "Morphling",
		"半人马战行者": "Centaur",
		"帕克": "Puck",
		"巫医": "Witch Docter",
		"潮汐猎人": "Tidehunter",
		"卓尔游侠": "Drow Ranger",
		"美杜莎": "Medusa",
		"露娜": "Luna",
		"巫妖": "Lich",
		"灰烬之灵": "Ember Spirit",
		"上古巨神": "Elder Titan",
		"虚空假面": "Faceless Void",
		"主宰": "Juggernaut",
		"冥魂大帝": "Skeleton King",
		"编织者": "Weaver",
		"寒冬飞龙": "Winter Wyvern",
		"裂魂人": "Spirit Breaker",
		"巨魔战将": "Troll Warlord",
		"撼地者": "Earthshaker",
		"育母蜘蛛": "Broodmother",
		"克林克兹": "Clinkz",
		"幽鬼": "Spectre",
		"斯拉达": "Slardar",
		"混沌骑士": "Chaos Knight",
		"发条技师": "Clockwerk",
		"酒仙": "Brewmaster",
		"复仇之魂": "Vengeful Spirit",
		"剃刀": "Razor",
		"炼金术士": "Alchemist",
		"大地之灵": "Earth Spirit",
		"瘟疫法师": "Necrolyte",
		"剧毒术士": "Venomancer",
		"兽王": "Beastmaster",
		"恐怖利刃": "Terroblade",
		"风暴之灵": "Storm Spirit",
		"先知": "Furion",
		"拉席克": "Leshrac",
		"狙击手": "Sniper",
		"圣堂刺客": "Templar Assasin",
		"凤凰": "Phoenix",
		"暗夜魔王": "Night Stalker",
		"工程师": "Techies",
		"暗影恶魔": "Shadow Demon",
		"莱恩": "Lion",
		"维萨吉": "Visage",
		"谜团": "Enigma",
		"帕吉": "Pudge",
		"幻影长矛手": "Phantom Lancer",
		"斧王": "Axe",
		"天怒法师": "Skywrath Mage"
	}
